; NOTE: This file was autogenerated by opcode_assigner.py
; Total opcode count: 24
; Zeropage opcodes: 24
; Extended opcodes: 0
#once
OP_NOP = 0x0000
OP_EXT = 0x0001
OP_BRK = 0x0002
OP_CLC = 0x0003
OP_MOV_A_B = 0x0004
OP_MOV_A_C = 0x0005
OP_MOV_A_D = 0x0006
OP_MOV_B_A = 0x0007
OP_MOV_B_C = 0x0008
OP_MOV_B_D = 0x0009
OP_MOV_C_A = 0x000a
OP_MOV_C_B = 0x000b
OP_MOV_C_D = 0x000c
OP_MOV_D_A = 0x000d
OP_MOV_D_B = 0x000e
OP_MOV_D_C = 0x000f
OP_MOV_A_DP = 0x0010
OP_MOV_DP_A = 0x0011
OP_LOAD_A_IMM = 0x0012
OP_LOAD_B_IMM = 0x0013
OP_LOAD_C_IMM = 0x0014
OP_LOAD_D_IMM = 0x0015
OP_ADC_A_B = 0x0016
OP_AND_A_B = 0x0017


