#include "bw8cpu.asm"

FALSE = 0x00
TRUE = 0xFF

SYS_BASE = 0x00
PIC_BASE = 0x01
UART_BASE = 0x02
SPI_BASE = 0x03
VDP_BASE = 0x04
PSG_BASE = 0x05
DMA_BASE = 0x07
KEY_BASE = 0x08
DEV10_BASE = 0x09
DEV11_BASE = 0x0A
DEV12_BASE = 0x0B
DEV13_BASE = 0x0C
DEV14_BASE = 0x0D
DEV15_BASE = 0x0E
DEV16_BASE = 0x0F

CLK_MODE        = SYS_BASE + 0
CLK_STEP        = 0b1111_1110
CLK_DEMO        = 0b1111_1101
CLK_FAST        = 0b1111_1011
GPIO_PORT       = SYS_BASE + 1
GPIO_DDR        = SYS_BASE + 2
GPIO_ANALOG_IN  = SYS_BASE + 3
GPIO_ANALOG_OUT = SYS_BASE + 4
GPIO_CONFIG     = SYS_BASE + 5

IRQ_SOURCE = PIC_BASE + 0
IRQ_MASK   = PIC_BASE + 1

DMA_SRC_BR = DMA_BASE + 0
DMA_SRC_HI = DMA_BASE + 1
DMA_SRC_LO = DMA_BASE + 2

DMA_DST_BR = DMA_BASE + 3
DMA_DST_HI = DMA_BASE + 4
DMA_DST_LO = DMA_BASE + 5

DMA_LEN_HI = DMA_BASE + 6
DMA_LEN_LO = DMA_BASE + 7

VOICE_1_FREQ_HI     = PSG_BASE + 0
VOICE_1_FREQ_LO     = PSG_BASE + 1
VOICE_1_FILTER_CTRL = PSG_BASE + 2
VOICE_1_CONFIG      = PSG_BASE + 3

VOICE_2_FREQ_HI     = PSG_BASE + 4
VOICE_2_FREQ_LO     = PSG_BASE + 5
VOICE_2_FILTER_CTRL = PSG_BASE + 6
VOICE_2_CONFIG      = PSG_BASE + 7

VOICE_3_FREQ_HI     = PSG_BASE + 8
VOICE_3_FREQ_LO     = PSG_BASE + 9
VOICE_3_FILTER_CTRL = PSG_BASE + 10
VOICE_3_CONFIG      = PSG_BASE + 11

VOICE_4_FREQ_HI     = PSG_BASE + 12
VOICE_4_FREQ_LO     = PSG_BASE + 13
VOICE_4_FILTER_CTRL = PSG_BASE + 14
VOICE_4_CONFIG      = PSG_BASE + 15

VRAM_BASE    = 0xC000
VRAM_BITMAP0 = VRAM_BASE + (0 * 1024)
VRAM_TILEMAP = VRAM_BASE + (8 * 1024)
VRAM_PALETTE = VRAM_BASE + (12 * 1024)
VRAM_END     = VRAM_BASE + (16 * 1024)

#ruledef sys_dependent_psuedo_ops {
    brk => asm{
        out <CLK_MODE>, #CLK_STEP
    }
}
