# NOTE: This file was autogenerated by opcode_assigner.py
# Total opcode count: 24
# Zeropage opcodes: 24
# Extended opcodes: 0
class Op:
    NOP = 0x0000
    EXT = 0x0001
    BRK = 0x0002
    CLC = 0x0003
    MOV_A_B = 0x0004
    MOV_A_C = 0x0005
    MOV_A_D = 0x0006
    MOV_B_A = 0x0007
    MOV_B_C = 0x0008
    MOV_B_D = 0x0009
    MOV_C_A = 0x000a
    MOV_C_B = 0x000b
    MOV_C_D = 0x000c
    MOV_D_A = 0x000d
    MOV_D_B = 0x000e
    MOV_D_C = 0x000f
    MOV_A_DP = 0x0010
    MOV_DP_A = 0x0011
    LOAD_A_IMM = 0x0012
    LOAD_B_IMM = 0x0013
    LOAD_C_IMM = 0x0014
    LOAD_D_IMM = 0x0015
    ADC_A_B = 0x0016
    AND_A_B = 0x0017


